#!/bin/python

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(a, hike_data):
    n = 0
    times = 0
    hike_data2 = []
    for x in range(0,len(hike_data)):
        if hike_data[x].upper() == 'U' :
            n = n + 1
            if n == 0 :
                times = times + 1
        elif hike_data[x].upper() == 'D' :
            n = n - 1
            if n == 0 :
                times = times + 1
    return times


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input())

    s = raw_input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
